[package]
name = "murk-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "C FFI bindings for the Murk simulation framework"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
murk-core = { path = "../murk-core" }
murk-engine = { path = "../murk-engine" }
murk-obs = { path = "../murk-obs" }
murk-space = { path = "../murk-space" }
murk-propagator = { path = "../murk-propagator" }
smallvec = { workspace = true }

[dev-dependencies]
murk-test-utils = { path = "../murk-test-utils" }
proptest = { workspace = true }
